name: mock
description: A dart library that mimics mockjs.
# version: 1.0.0
# homepage: https://github.com/zzzz1997/mock
# author: zzzz1997 <2549821359@qq.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  intl: ^0.16.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
